# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcmcProbitX <- function(Y, Ylatent, X, paramX, meansParamX, precX, residVar, priorMeansParamX, priorVarXScaleMat, priorVarXDf, priorResidVarScale, priorResidVarShape, nsp, nsite, nparamX, niter, nburn, thin, verbose) {
    .Call('HMSC_mcmcProbitX', PACKAGE = 'HMSC', Y, Ylatent, X, paramX, meansParamX, precX, residVar, priorMeansParamX, priorVarXScaleMat, priorVarXDf, priorResidVarScale, priorResidVarShape, nsp, nsite, nparamX, niter, nburn, thin, verbose)
}

#' @title Sample from a multivariate Normal distribution.
#' 
#' @description Produces one or more samples from the specified multivariate normal distribution. Unlike the function \code{\link{mvrnorm}[MASS]}, this function is very simple and does not perform the many checks carried out in the \code{\link{mvrnorm}[MASS]}. For this reason, it is faster but it must be used carefully as it may lead to some unexpected error. This function is only meant to be used internally.
#'
#' @param n Numeric. Number of samples.
#' @param Mean A vector giving the means of the variables sampled. 
#' @param Var A positive-definite symmetric matrix specifying the covariance matrix of the variables.
#'
#' @export
rmvnorm <- function(n, Mean, Var) {
    .Call('HMSC_rmvnorm', PACKAGE = 'HMSC', n, Mean, Var)
}

sampleCondPred <- function(Y, EstModel, residVar, nsite, nsp, niter, nsample, family) {
    .Call('HMSC_sampleCondPred', PACKAGE = 'HMSC', Y, EstModel, residVar, nsite, nsp, niter, nsample, family)
}

#' @title Sample the model response matrix
#'
#' @description Sample the model response matrix after the Poisson link function was applied. This function is meant to be used internally.
#'
#' @param Y The species community matrix to be modelled.
#' @param Ylatent Model site by species community matrix after the link function is applied.
#' @param EstModel Estimated model for the site by species community matrix.
#' @param residVar Vector of parameters with as many entries as there are species. Each values in this vector describes how much variation is not explained by the model. This vector should only contains 1s, but it was included in this function to deal with potential situations that may arise (in other words, in case I forgot a special case).
#' @param nsp Numeric. Number of species in \code{Y}.
#' @param nsite Numeric. Number of site sampled.
#'
#' @export
sampleYlatentPoisson <- function(Y, Ylatent, EstModel, residVar, nsp, nsite) {
    .Call('HMSC_sampleYlatentPoisson', PACKAGE = 'HMSC', Y, Ylatent, EstModel, residVar, nsp, nsite)
}

#' @title Sample the model response matrix
#'
#' @description Sample the model response matrix after the Probit link function was applied. This function is meant to be used internally.
#'
#' @param Y0Loc A vector defining the locations of all 0s in the community matrix (\code{Y}).
#' @param Y1Loc A vector defining the locations of all 1s in the community matrix (\code{Y}).
#' @param Ylatent Model site by species community matrix after the link function is applied.
#' @param EstModel Estimated model for the site by species community matrix.
#' @param residVar Vector of parameters with as many entries as there are species. Each values in this vector describes how much variation is not explained by the model. This vector should only contains 1s, but it was included in this function to deal with potential situations that may arise (in other words, in case I forgot a special case).
#' @param nsp Numeric. Number of species in \code{Y}.
#' @param nsite Numeric. Number of site sampled.
#'
#' @export
sampleYlatentProbit <- function(Y0Loc, Y1Loc, Ylatent, EstModel, residVar, nsp, nsite) {
    .Call('HMSC_sampleYlatentProbit', PACKAGE = 'HMSC', Y0Loc, Y1Loc, Ylatent, EstModel, residVar, nsp, nsite)
}

